# Azam's Professional Portfolio Automation
# Har 5 minute baad auto-check karega

schedules:
- cron: "*/2 * * * *"
  displayName: "Every 5 Minutes Auto-Sync"
  branches:
    include: [main]
  always: true

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: AzureWebApp@1
  displayName: 'Deploy Portfolio to Azure'
  inputs:
    azureSubscription: 'AzamServiceConn'
    appType: 'webApp'
    appName: 'azam-portfolio-web' # <-- Agar portal par naam kuch aur hai toh bas ye badal dena
    package: '$(System.DefaultWorkingDirectory)'