name: Azam Azure Automation

on:
  workflow_dispatch: # Button dabane par chalega

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Code Download
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check Azure Connection
        run: az account show
